/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import okhttp3.Request;
import okhttp3.Response;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import okhttp3.OkHttpClient;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

class LibraryTest {
    static String DB_URL = "jdbc:postgresql://localhost:5432/movies";
    static String DB_USER = "postgres";
    static String DB_PASSWORD = "postgres";
    @Test void AppReturnMovieGenres() {
        OkHttpClient client = new OkHttpClient();

        Request request = new Request.Builder().url("http://localhost:4000/v1/genres").build();

        try {
            String response = client.newCall(request).execute().body().string();
            assertTrue(response.contains("Adventure"));
        } catch (Exception e) {fail("Exception occurred: " + e.getMessage());}
    }

    @Test void moviesListIsNotEmpty() {

        String filmTitles = "";
        try {
            Class.forName("org.postgresql.Driver");
            Connection connection = (Connection) DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM movies LIMIT 1");
            while (resultSet.next()) {
                filmTitles = resultSet.getString("title");
            }
            System.out.println(filmTitles);
            connection.close();
        } catch (Exception e) {fail("Exception occurred: " + e.getMessage());}


        OkHttpClient client = new OkHttpClient();

        Request request = new Request.Builder().url("http://localhost:4000/v1/movies").build();

        try {
            String response = client.newCall(request).execute().body().string();
            assertTrue(response.contains("\"title\":\" + filmTitles + \""));
        } catch (Exception e) {fail("Exception occurred: " + e.getMessage());}
    }
}

